-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE staging.softcartdimcategory
(
    categoryid integer NOT NULL,
    categoryname character varying(50),
    parentcategory character varying(50),
    PRIMARY KEY (categoryid)
);

CREATE TABLE staging.softcartdimcountry
(
    countryid integer NOT NULL,
    countryname character varying(50),
    region character varying(50),
    PRIMARY KEY (countryid)
);

CREATE TABLE staging.softcartdimdate
(
    dateid integer NOT NULL,
    day integer,
    month integer,
    monthname character varying(10),
    year integer,
    weekday character varying(10),
    PRIMARY KEY (dateid)
);

CREATE TABLE staging.softcartdimitem
(
    itemid integer NOT NULL,
    itemname character varying(100),
    itemdescription character varying(200),
    categoryid integer,
    PRIMARY KEY (itemid)
);

CREATE TABLE staging.softcartfactsales
(
    orderid integer NOT NULL,
    item integer,
    category integer,
    price numeric(10, 2),
    country integer,
    date integer,
    PRIMARY KEY (orderid)
);

ALTER TABLE staging.softcartdimitem
    ADD FOREIGN KEY (categoryid)
    REFERENCES public.softcartdimcategory (categoryid)
    NOT VALID;


ALTER TABLE staging.softcartfactsales
    ADD FOREIGN KEY (category)
    REFERENCES public.softcartdimcategory (categoryid)
    NOT VALID;


ALTER TABLE staging.softcartfactsales
    ADD FOREIGN KEY (country)
    REFERENCES public.softcartdimcountry (countryid)
    NOT VALID;


ALTER TABLE staging.softcartfactsales
    ADD FOREIGN KEY (date)
    REFERENCES public.softcartdimdate (dateid)
    NOT VALID;


ALTER TABLE staging.softcartfactsales
    ADD FOREIGN KEY (item)
    REFERENCES public.softcartdimitem (itemid)
    NOT VALID;

END;